name: Auto‐update LooksRare Sheet

# 定时＋手动触发
on:
  schedule:
    # 每小时整点运行一次
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  # 允许写入仓库内容（用于 push 回 CSV）
  contents: write

jobs:
  update-sheet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # 保留 GITHUB_TOKEN，以便后面 push 使用
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --no-cache-dir \
            requests pandas web3 \
            gspread oauth2client gspread-dataframe

      - name: Write Google credentials
        env:
          # 你需要在仓库 Settings → Secrets → Actions 里新增一个
          # 名为 GOOGLE_CREDENTIALS 的 secret，其值填 Service Account JSON 全文
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "$GOOGLE_CREDENTIALS" > credentials.json

      - name: Fetch on-chain data
        run: python fetch_sales.py

      - name: Upload to Google Sheets
        run: python upload_to_sheets.py looksrare_takerAsks.csv --credentials credentials.json

      - name: Commit CSV back
        run: |
          git config user.name 'github-actions'
          git config user.email 'actions@github.com'
          git add looksrare_takerAsks.csv
          git commit -m "chore: hourly update CSV" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
